routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('user', 'UserController', ['except' => ['update']]);
    Route::post('user/{id}', 'UserController@update')->name('user.update');
    Route::get('user/data/table', 'UserController@userDataTable')->name('user.table');

    Route::resource('book', 'BookController', ['except' => ['update']]);
    Route::post('book/{id}', 'BookController@update')->name('book.update');
    Route::get('book/data/table', 'BookController@bookDataTable')->name('book.table');

    Route::resource('book_category', 'BookCategoryController', ['except' => ['update']]);
    Route::post('book_category/{id}', 'BookCategoryController@update')->name('book_category.update');
    Route::get('book_category/data/table', 'BookCategoryController@bookCategoryDataTable')->name('book_category.table');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Dashboard
                    <a class="btn btn-outline-success modal-show float-right" title="Tambah Data" href="{{ route('user.create') }}"> Tambah Data</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>

                <div class="card-body" id="user">
                    <div class="table-responsive py-8">
                        <input type="hidden" id="data-url" value="{{ route('user.table') }}"/>
                        <table class="table tablese table-flush" id="user-table" style="width:100%;">
                            <thead class="thead-light">
                                <tr>
                                    <th style="width:5%;">No</th>
                                    <th>ID</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th style="width:5%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection