routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('user', 'UserController', ['except' => ['update']]);
    Route::post('user/{id}', 'UserController@update')->name('user.update');
    Route::get('user/data/table', 'UserController@userDataTable')->name('user.table');

    Route::resource('book', 'BookController', ['except' => ['update']]);
    Route::post('book/{id}', 'BookController@update')->name('book.update');
    Route::get('book/data/table', 'BookController@bookDataTable')->name('book.table');

    Route::resource('book_category', 'BookCategoryController', ['except' => ['update']]);
    Route::post('book_category/{id}', 'BookCategoryController@update')->name('book_category.update');
    Route::get('book_category/data/table', 'BookCategoryController@bookCategoryDataTable')->name('book_category.table');
});

app/Models/BookCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BookCategory extends Model
{
    protected $table = 'book_category';
    
    protected $fillable = ['name'];

    public function book(){
        return $this->hasMany('App\Models\Book', 'category_id');
    }
}

app/Http/Controllers/BookCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\BookCategory;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class BookCategoryController extends Controller
{
    private $bookCategory;

    function __construct(BookCategory $bookCategory, DataTables $dataTable)
    {   
        $this->bookCategory = $bookCategory;
        $this->dataTable = $dataTable;
    }

    public function index()
    {
        return view('book_category.index');
    }


    public function create()
    {
        $model = new $this->bookCategory;
        return view('book_category.form', compact('model'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);
        
        $model = $this->bookCategory->create($request->all());
        return response()->json($model);
    }

    public function show($id)
    {
        $model = $this->bookCategory->findorFail($id);
        return view('book_category.form', compact('model'));  
    }

    public function edit($id)
    {
        $model = $this->bookCategory->findorFail($id);
        return view('book_category.form', compact('model'));   
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);
        
        $model = $this->bookCategory->findorFail($id);

        return response()->json($model->update($request->all()));
    }

    public function destroy($id)
    {
        $model = $this->bookCategory->findorFail($id);

        return response()->json($model->delete());
    }

    public function bookCategoryDataTable()
    {
        return $this->dataTable->of($this->bookCategory->all())
            ->addIndexColumn()
            ->toJson();
    }
}

resources/views/book_category/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['book_category.update', $model->id] : 'book_category.store',
    'id' => 'test-aqi-form'  
]) !!}
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Nama *</label>
                {!! Form::text('name',null,['class' => 'form-control', 'id' => 'name']) !!}
            </div>
        </div>
    </div>
{!! Form::close() !!}

resources/views/book_category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Kategori Buku
                    <a class="btn btn-outline-success modal-show float-right" title="Tambah Data" href="{{ route('book_category.create') }}"> Tambah Data</a>
                </div>


                <div class="card-body" id="book-category">
                    <div class="table-responsive py-8">
                        <input type="hidden" id="data-url" value="{{ route('book_category.table') }}"/>
                        <table class="table tablese table-flush" id="book-category-table" style="width:100%;">
                            <thead class="thead-light">
                                <tr>
                                    <th style="width:5%;">No</th>
                                    <th>ID</th>
                                    <th>Nama</th>
                                    <th style="width:5%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection