routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('user', 'UserController', ['except' => ['update']]);
    Route::post('user/{id}', 'UserController@update')->name('user.update');
    Route::get('user/data/table', 'UserController@userDataTable')->name('user.table');

    Route::resource('book', 'BookController', ['except' => ['update']]);
    Route::post('book/{id}', 'BookController@update')->name('book.update');
    Route::get('book/data/table', 'BookController@bookDataTable')->name('book.table');

    Route::resource('book_category', 'BookCategoryController', ['except' => ['update']]);
    Route::post('book_category/{id}', 'BookCategoryController@update')->name('book_category.update');
    Route::get('book_category/data/table', 'BookCategoryController@bookCategoryDataTable')->name('book_category.table');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $table = 'book';

    protected $fillable = [
        'title', 'description', 'category', 'keywords', 'price', 'stock', 'publisher'
    ];

    public function category(){
        return $this->belongsTo('App\Models\BookCategory');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use DB;

class BookController extends Controller
{
    private $book;

    function __construct(Book $book, DataTables $dataTable)
    {   
        $this->book = $book;
        $this->dataTable = $dataTable;
    }

    public function index()
    {
        return view('book.index');
    }

    public function create()
    {
        $model = new $this->book;
        $category = DB::table('book_category')->pluck('name', 'name');
        return view('book.form', compact('model', 'category'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'category' => 'required',
            'keywords' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'publisher' => 'required',
        ]);
        
        $input = $request->all();
        $input['category'] = implode(', ', $request->category);
        $model = $this->book->create($input);
        return response()->json($model);
    }

    public function show($id)
    {
        $model = $this->book->findOrFail($id);
        $category = DB::table('book_category')->pluck('name', 'id');
        return view('book.form', compact('model', 'category'));
    }

    public function edit($id)
    {
        $model = $this->book->findOrFail($id);
        $category = DB::table('book_category')->pluck('name', 'name');
        return view('book.form', compact('model', 'category'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'category' => 'required',
            'keywords' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'publisher' => 'required',
        ]);
        
        $input = $request->all();
        $input['category'] = implode(', ', $request->category);

        $model = $this->book->findOrFail($id);
        
        return response()->json($model->update($input));
    }

    public function destroy($id)
    {
        $model = $this->book->findorFail($id);

        return response()->json($model->delete());
    }

    public function bookDataTable()
    {

        return $this->dataTable->of($this->book->all())
            ->addIndexColumn()
            ->toJson();
    }
}

resources/views/book/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['book.update', $model->id] : 'book.store',
    'id' => 'test-aqi-form'  
]) !!}
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Judul Buku</label>
                {!! Form::text('title',null,['class' => 'form-control', 'id' => 'title']) !!}
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Deskripsi</label>
                {!! Form::text('description',null,['class' => 'form-control', 'id' => 'description']) !!}
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Kategori</label>
                {!! Form::select('category[]', $category, null,['class' => 'form-control', 'multiple' => 'multiple', 'id' => 'category']) !!}
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Keywords</label>
                {!! Form::text('keywords', null,['class' => 'form-control', 'id' => 'keywords']) !!}
                <small id="keywords" class="form-text text-muted">*) Pisahkan dengan tanda koma (eg. RUP, SCRUM, Agile)</small>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Harga</label>
                {!! Form::number('price',null,['class' => 'form-control', 'id' => 'price', 'min' => '0']) !!}
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Stock</label>
                {!! Form::number('stock',null,['class' => 'form-control', 'id' => 'stock', 'min' => '0']) !!}
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label class="form-control-label">Penerbit</label>
                {!! Form::text('publisher',null,['class' => 'form-control', 'id' => 'publisher']) !!}
            </div>
        </div>
    </div>
{!! Form::close() !!}

resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Daftar Buku
                    <a class="btn btn-outline-success modal-show float-right" title="Tambah Data" href="{{ route('book.create') }}"> Tambah Data</a>
                </div>


                <div class="card-body" id="book">
                    <div class="table-responsive py-8">
                        <input type="hidden" id="data-url" value="{{ route('book.table') }}"/>
                        <table class="table tablese table-flush" id="book-table" style="width:100%;">
                            <thead class="thead-light">
                                <tr>
                                    <th style="width:5%;">No</th>
                                    <th>ID</th>
                                    <th>Judul Buku</th>
                                    <th>Description</th>
                                    <th>Kategori</th>
                                    <th>Keywords</th>
                                    <th>Harga</th>
                                    <th>Stock</th>
                                    <th>Penerbit</th>
                                    <th style="width:5%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection